const imageData = [
  {
    id: 0,
    url: "sitting-room-from-dining-area.jpg",
    title: "Sitting room from dining area",
    description: "The living room has comfy seating and a cosy gas log-effect stove",
    width: "2500",
    height: "1668",
  },
  {
    id: 1,
    url: "dining-area-from-sitting-room.jpg",
    title: "Dining area from-sitting room",
    description: "The dining area has a view of the garden and countryside beyond",
    width: "2500",
    height: "1668",
  },
  {
    id: 2,
    url: "bedroom-towards-window.jpg",
    title: "Bedroom towards the window",
    description: "The bedroom mullion window overlooks the fields and woodland behind the house",
    width: "2500",
    height: "1668",
  },
  {
    id: 50,
    url: "sauna-general.jpg",
    title: "Sauna and spa",
    description: "The sauna has plenty of room to relax after your session.",
    width: "3559",
    height: "4001",
  },
  {
    id: 4,
    url: "entrance-bootroom.jpg",
    title: "Entrance and bootroom",
    description: "The entrance has space for storing walking boots and coats, plus a fridge-freezer and microwave.",
    width: "2500",
    height: "3423",
  },
  {
    id: 5,
    url: "kitchen-from-entrance.jpg",
    name: "kitchen-from-entrance",
    title: "Kitchen from entrance",
    description: "The galley kitchen has every modern appliance",
    width: "2500",
    height: "2531",
  },
  {
    id: 6,
    url: "seating-outside-french-windows.jpg",
    title: "Seating outside French windows",
    description: "A sitting area where you can enjoy some evening sunshine just outside the French windows",
    width: "2500",
    height: "1724",
  },
  {
    id: 30,
    url: "shower-room.jpg",
    title: "Shower room and toilet",
    description: "A spacious shower room and toilet",
    width: "2500",
    height: "1668",
  },
];

export default imageData;
